CREATE TABLE COUNTRY (
  empId INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  dept TEXT NOT NULL
);
-- insert
INSERT INTO COUNTRY VALUES (0001, 'BISHKEK', 'UZ');
INSERT INTO COUNTRY VALUES (0002, 'ALMATY', 'KZ');
INSERT INTO COUNTRY VALUES (0003, 'AKTOBE', 'KZ');
INSERT INTO COUNTRY VALUES (0004, 'ASTANA', 'KZ'); 
-- fetch 

SELECT * from COUNTRY
WHERE empId='0001'
